- name: Install dependencies
  ansible.builtin.apt:
    name:
      - snapd
      - squashfuse
      - fuse
    state: present

- name: Install Overseerr
  community.general.snap:
    name:
      - core
      - overseerr
    state: present

- name: Start Overseerr service
  ansible.builtin.systemd:
    name: snap.overseerr.daemon.service
    state: started
