- name: Configure PVE nodes
  hosts: pve-nodes
  remote_user: root
  tasks:
    # https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh
    - name: Suppress non-free firmware warnings
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
        line: APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        create: true
        state: present

    - name: Disable ceph enterprise repository
      ansible.builtin.lineinfile:
        path: /ect/apt/sources.list.d/ceph.list
        regex: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
        line: "# deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise"
        state: present

    - name: Disable pve-enterprise repository
      ansible.builtin.lineinfile:
        path: /ect/apt/sources.list.d/pve-enterprise.list
        regex: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
        line: "# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise"
        state: present

    - name: Enable pve-no-subscription repository
      ansible.builtin.lineinfile:
        path: /ect/apt/sources.list.d/pve-no-subscription.list
        line: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        create: true
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        state: present

    - name: Disable subscription nag
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/disable-subscription-nag
        line: DPkg::Post-Invoke { "dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ $? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/.*data\.status.*{/{s/\!//;s/active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi"; };
        create: true
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        state: present

    - name: Enable high availability services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - pve-ha-lrm
        - pve-ha-crm
        - corosync

    # https://forum.proxmox.com/threads/tutorial-unprivileged-lxcs-mount-cifs-shares.101795/
    - name: Add media share mount for use in LXC containers
      ansible.posix.mount:
        src: //10.0.10.16/media
        path: /mnt/lxc_shares/media/
        opts: _netdev,x-systemd.automount,noatime,uid=100000,gid=100900,dir_mode=0770,file_mode=0770,credentials=/root/media_share.creds
        fstype: cifs
        boot: true
        state: mounted
