- name: Apply common configurations to servarr hosts
  hosts: servarr
  roles:
    - role: create_user
      user: "{{ ansible_user }}"
    - role: create_group
      group: "{{ media_group }}"
    - role: create_user
      user: "{{ personal_user }}"

- name: Configure redbeard
  hosts: redbeard
  roles:
    - mullvad
    - qbittorrent
    - sabnzbd

- name: Configure prowlarr
  hosts: prowlarr
  roles:
    - prowlarr

- name: Configure radarr
  hosts: radarr
  roles:
    - radarr

- name: Configure sonarr
  hosts: sonarr
  roles:
    - sonarr

- name: Configure lidarr
  hosts: lidarr
  roles:
    - lidarr

- name: Configure readarr
  hosts: readarr
  roles:
    - readarr

- name: Configure bazarr
  hosts: bazarr
  roles:
    - bazarr
