- name: Install ddclient
  ansible.builtin.apt:
    name: ddclient
    state: present

- name: Create configuration file
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    owner: root
    group: root
    mode: u=rw,g=,o=

- name: Start ddclient service
  ansible.builtin.systemd:
    name: ddclient.service
    state: started
    enabled: true
    daemon_reload: true
