- name: Create install directory
  ansible.builtin.file:
    path: "{{ lidarr_install_dir }}"
    owner: "{{ lidarr_user.name }}"
    group: "{{ lidarr_user.name }}"
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ lidarr_dependencies }}"
    state: present

- name: Download and install release
  ansible.builtin.unarchive:
    src: "{{ lidarr_download_url }}"
    dest: "{{ lidarr_install_dir }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
    owner: "{{ lidarr_user.name }}"
    group: "{{ lidarr_user.name }}"
    mode: u=rwx,g=rx,o=rx

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ lidarr_config_dir }}"
    owner: "{{ lidarr_user.name }}"
    group: "{{ lidarr_user.name }}"
    mode: u=rwx ,g=rx,o=rx
    state: directory

- name: Create systemd service
  ansible.builtin.template:
    src: lidarr.service.j2
    dest: /etc/systemd/system/lidarr.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start lidarr service
  ansible.builtin.systemd:
    name: lidarr.service
    state: started
    enabled: true
    daemon_reload: true
