- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound.service
    state: restarted

- name: Run unbound-control-setup
  ansible.builtin.command: unbound-control-setup
  changed_when: true
