- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Download deb package
  ansible.builtin.get_url:
    url: "{{ mullvad_download_url }}"
    dest: "{{ temp_dir.path }}"
  register: download

- name: Install deb package
  ansible.builtin.apt:
    deb: "{{ download.dest }}"

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent
  when: temp_dir.path is defined

