- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ readarr_dependencies }}"
    state: present

- name: Download and install release
  ansible.builtin.unarchive:
    src: "{{ readarr_download_url }}"
    dest: "{{ readarr_install_dir }}"
    remote_src: true
    owner: "{{ readarr_user.name }}"
    group: "{{ readarr_user.name }}"
    mode: u=rwx,g=rx,o=rx

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ readarr_config_dir }}"
    owner: "{{ readarr_user.name }}"
    group: "{{ readarr_user.name }}"
    mode: u=rw,g=r,o=r
    state: directory

- name: Create systemd service
  ansible.builtin.template:
    src: readarr.service.j2
    dest: /etc/systemd/system/readarr.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start readarr service
  ansible.builtin.systemd:
    name: readarr.service
    state: started
    enabled: true
    daemon_reload: true
