pve_create_ct_operating_systems:
  debian: debian-12-standard_12.2-1_amd64.tar.zst
  devuan: devuan-4.0-standard_4.0_amd64.tar.gz
  ubuntu: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
  centos: centos-9-stream-default_20221109_amd64.tar.xz
  fedora: fedora-39-default_20231118_amd64.tar.xz
  opensuse: opensuse-15.5-default_20231118_amd64.tar.xz
  archlinux: archlinux-base_20230608-1_amd64.tar.zst
  alpine: alpine-3.19-default_20240207_amd64.tar.xz
  gentoo: gentoo-current-openrc_20231009_amd64.tar.xz

pve_create_ct_rootfs: >-
  {{ ct.rootfs.volume | mandatory }}:{{ ct.rootfs.size | mandatory }}
  {%- if ct.rootfs.acl is defined %},acl={{ ct.rootfs.acl | ternary(1, 0) }}{% endif -%}
  {%- if ct.rootfs.options is defined %},mountoptions={{ ct.rootfs.options | join(';') }}{% endif -%}
  {%- if ct.rootfs.quota is defined %},quota={{ ct.rootfs.quota | ternary(1, 0) }}{% endif -%}
  {%- if ct.rootfs.replicate is defined %},replicate={{ ct.rootfs.replicate | ternary(1, 0) }}{% endif -%}
  {%- if ct.rootfs.shared is defined %},shared={{ ct.rootfs.shared | ternary(1, 0) }}{% endif -%}

pve_create_ct_mount_points: >-
  {%- if ct.mount_points is defined -%}
  {%- for mp in ct.mount_points -%}
  mp{{ loop.index0 }}: >
    {{ mp.volume | mandatory }}{%- if mp.size is defined %}:{{ mp.size }}{% endif -%}
    ,mp={{ mp.path | mandatory }}
    {%- if mp.acl is defined %},acl={{ mp.acl | ternary(1, 0) }}{% endif -%}
    {%- if mp.backup is defined %},backup={{ mp.backup | ternary(1, 0) }}{% endif -%}
    {%- if mp.options is defined %},mountoptions={{ mp.options | join(';') }}{% endif -%}
    {%- if mp.quota is defined %},quota={{ mp.quota | ternary(1, 0) }}{% endif -%}
    {%- if mp.replicate is defined %},replicate={{ mp.replicate | ternary(1, 0) }}{% endif -%}
    {%- if mp.read_only is defined %},ro={{ mp.read_only | ternary(1, 0) }}{% endif -%}
    {%- if mp.shared is defined %},shared={{ mp.shared | ternary(1, 0) }}{% endif -%}
  {%- endfor -%}
  {%- endif -%}

pve_create_ct_network_interfaces: >-
  {%- for nic in ct.network_interfaces -%}
  net{{ loop.index0 }}: >
    name={{ nic.name | mandatory }}
    {%- if nic.bridge is defined %},bridge={{ nic.bridge }}{% endif -%}
    {%- if nic.mac_address is defined %},hwaddr={{ nic.mac_address }}{% endif -%}
    {%- if nic.firewall is defined %},firewall={{ nic.firewall | ternary(1, 0) }}{% endif -%}
    {%- if nic.ipv4.gateway is defined %},gw={{ nic.ipv4.gateway }}{% endif -%}
    {%- if nic.ipv4.address is defined %},ip={{ nic.ipv4.address }}{% endif -%}
    {%- if nic.ipv6.gateway is defined %},gw6={{ nic.ipv6.gateway }}{% endif -%}
    {%- if nic.ipv6.address is defined %},ip6={{ nic.ipv6.address }}{% endif -%}
    {%- if nic.link_down is defined %},link_down={{ nic.link_down | ternary(1, 0) }}{% endif -%}
    {%- if nic.mtu is defined %},mtu={{ nic.mtu }}{% endif -%}
    {%- if nic.rate is defined %},rate={{ nic.rate }}{% endif -%}
    {%- if nic.tag is defined %},tag={{ nic.tag }}{% endif -%}
    {%- if nic.trunks is defined %},trunks={{ nic.trunks | join(';') }}{% endif -%}
  {%- endfor -%}

pve_create_ct_features:
  - "{% if ct.features.force_rw_sys is defined %}force_rw_sys={{ ct.features.force_rw_sys | ternary(1, 0) }}{% endif %}"
  - "{% if ct.features.fuse is defined %}fuse={{ ct.features.fuse | ternary(1, 0) }}{% endif %}"
  - "{% if ct.features.keyctl is defined %}keyctl={{ ct.features.keyctl | ternary(1, 0) }}{% endif %}"
  - "{% if ct.features.mknod is defined %}mknod={{ ct.features.mknod | ternary(1, 0) }}{% endif %}"
  - "{% if ct.features.mount is defined %}mount={{ ct.features.mount | join(';') }}{% endif %}"
  - "{% if ct.features.nesting is defined %}nesting={{ ct.features.nesting | ternary(1, 0) }}{% endif %}"

pve_create_ct_startup:
  - "{{ ct.startup.order is defined | ternary('order=' + ct.startup.order, omit) }}"
  - "{{ ct.startup.up_delay is defined | ternary('up=' + ct.startup.up_delay, omit) }}"
  - "{{ ct.startup.down_delay is defined | ternary('down=' + ct.startup.down_delay, omit) }}"
