- name: Create install directory
  ansible.builtin.file:
    path: "{{ radarr_install_dir }}"
    owner: "{{ radarr_user.name }}"
    group: "{{ radarr_user.name }}"
    mode: u=rw,g=r,o=r
    state: directory

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ radarr_dependencies }}"
    state: present

- name: Download and install release
  ansible.builtin.unarchive:
    src: "{{ radarr_download_url }}"
    dest: "{{ radarr_install_dir }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
    owner: "{{ radarr_user.name }}"
    group: "{{ radarr_user.name }}"
    mode: u=rwx,g=rx,o=rx

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ radarr_config_dir }}"
    owner: "{{ radarr_user.name }}"
    group: "{{ radarr_user.name }}"
    mode: u=rw,g=r,o=r
    state: directory

- name: Create systemd service
  ansible.builtin.template:
    src: radarr.service.j2
    dest: /etc/systemd/system/radarr.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start radarr service
  ansible.builtin.systemd:
    name: radarr.service
    state: started
    enabled: true
    daemon_reload: true
