bazarr_download_url: https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip

bazarr_user:
  name: bazarr
  uid: 915
  create_home: true
  groups:
    - media
  shell: /usr/sbin/nologin
  system: true

bazarr_dependencies:
  - 7zip
  - python3-dev
  - python3-pip
  - python3-distutils
  - unrar # requires non-free repository
  - unzip
