- name: Install Node.js
  ansible.builtin.apt:
    name: "{{ uptime_kuma_dependencies }}"
    state: present

- name: Create install directory
  ansible.builtin.file:
    path: "{{ uptime_kuma_install_dir }}"
    owner: "{{ uptime_kuma_user.name }}"
    group: "{{ uptime_kuma_user.name }}"
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Clone repository
  become: true
  become_user: "{{ uptime_kuma_user.name }}"
  ansible.builtin.git:
    repo: https://github.com/louislam/uptime-kuma.git
    dest: "{{ uptime_kuma_install_dir }}"
    version: "{{ uptime_kuma_version }}"

- name: Install dependencies
  community.general.npm:
    path: "{{ uptime_kuma_install_dir }}"
    ci: true
    production: true
    executable: /bin/npm
    state: present

- name: Allow non-root users to use ping command
  community.general.capabilities:
    path: /bin/ping
    capability: CAP_NET_RAW=+eip
    state: present

- name: Create systemd service
  ansible.builtin.template:
    src: uptime-kuma.service.j2
    dest: /etc/systemd/system/uptime-kuma.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start uptime-kuma service
  ansible.builtin.systemd:
    name: uptime-kuma.service
    state: started
    enabled: true
    daemon_reload: true
