- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ qbittorrent_dependencies }}"
    state: present

- name: Install qbittorrent
  ansible.builtin.apt:
    name: qbittorrent-nox
    state: present

- name: Create systemd service
  ansible.builtin.template:
    src: qbittorrent.service.j2
    dest: /etc/systemd/system/qbittorrent.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start qbittorrent daemon
  ansible.builtin.systemd:
    name: qbittorrent.service
    state: started
    enabled: true
    daemon_reload: true
