- name: Create install directory
  ansible.builtin.file:
    path: "{{ sonarr_install_dir }}"
    owner: "{{ sonarr_user.name }}"
    group: "{{ sonarr_user.name }}"
    mode: u=rw,g=r,o=r
    state: directory

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ sonarr_dependencies }}"
    state: present

- name: Download and install release
  ansible.builtin.unarchive:
    src: "{{ sonarr_download_url }}"
    dest: "{{ sonarr_install_dir }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
    owner: "{{ sonarr_user.name }}"
    group: "{{ sonarr_user.name }}"
    mode: u=rwx,g=rx,o=rx

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ sonarr_config_dir }}"
    owner: "{{ sonarr_user.name }}"
    group: "{{ sonarr_user.name }}"
    mode: u=rw,g=r,o=r
    state: directory

- name: Create systemd service
  ansible.builtin.template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start sonarr service
  ansible.builtin.systemd:
    name: sonarr.service
    state: started
    enabled: true
    daemon_reload: true
