- name: Add Plex Media Server repository
  ansible.builtin.deb822_repository:
    name: plexmediaserver
    types: deb
    uris: https://downloads.plex.tv/repo/deb/
    suites: public
    components: main
    signed_by: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present
  register: plex_media_server_repository

- name: Install Plex Media Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: "{{ plex_media_server_repository.changed }}"
