- name: Fetch and install updates
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    upgrade: full

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
