- name: Create ansible user
  ansible.builtin.include_role:
    name: create_user
  vars:
    user: "{{ ansible_user }}"

- name: Create media group
  ansible.builtin.include_role:
    name: create_group
  vars:
    group: "{{ media_group }}"

