- name: Create user primary group
  when: user.group is undefined or user.group == user.name
  ansible.builtin.group:
    name: "{{ user.name }}"
    gid: "{{ user.uid }}"
    system: "{{ user.system | default(omit) }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    uid: "{{ user.uid }}"
    create_home: "{{ user.create_home | default(omit) }}"
    home: "{{ user.home | default(omit) }}"
    group: "{{ user.group | default(user.name) }}"
    groups: "{{ user.groups | default(omit) }}"
    password: "{{ user.password | default('!') }}"
    shell: "{{ user.shell | default('/usr/bin/nologin') }}"
    system: "{{ user.system | default(omit) }}"
    state: present

- name: Add user's SSH key
  when: user.authorized_key is defined
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.authorized_key }}"
    state: present
