ansible_user:
  name: squ4tch
  uid: 67
  create_home: true
  groups:
    - sudo
  shell: /bin/bash
  system: true
  authorized_key: "{{ lookup('file', '/home/squ4tch/.ssh/id_25519.pub') }}"

media_group:
  name: media
  gid: 900
  system: true

