- name: Create group {{ group.name ~ '(' ~ group.uid ~ ')' }}
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.gid }}"
    system: "{{ group.system | default(omit) }}"
    state: present
